### ISSUE TITLE
purging of older backup files fails, due to the directories being older than the retention period

### ISSUE THREAD

**Issue by jneo8** [canonical/charm-juju-backup-all#2]
Purging of older backup files fails, due to the directories being older than the retention period and not empty (due to recent backups). Stacktrace example below.

The charm Should only remove the backup files themselves (regular files) and ignore the directories.

2022-01-02 04:36:10,439 INFO __main__ purging backup files older than: '30' days
find: cannot delete ‘/opt/backups/controller/openstack’: Directory not empty
find: cannot delete ‘/opt/backups’: Permission denied
2022-01-02 04:36:10,452 ERROR __main__ 
2022-01-02 04:36:10,453 DEBUG __main__ writing error details to the results file
2022-01-02 04:36:10,453 ERROR __main__ backup failed! check log for details
Traceback (most recent call last):
  File "/var/lib/jujubackupall/auto_backup.py", line 154, in <module>
    auto_backup.run()
  File "/var/lib/jujubackupall/auto_backup.py", line 133, in run
    self.purge_old_backups(args.purge_after_days)
  File "/var/lib/jujubackupall/auto_backup.py", line 86, in purge_old_backups
    subprocess.check_output(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['find', '/opt/backups', '-mtime', '+30', '-delete']' returned non-zero exit status 1.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2022-01-06T07:11:23Z
 * owner: [jfguedez](https://launchpad.net/~jfguedez)
 * assignee: [jfguedez](https://launchpad.net/~jfguedez)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1956558)

**Comment by jneo8** [comment]
(by [jfguedez](https://launchpad.net/~jfguedez))
Released in cs:~bootstack-charmers/juju-backup-all-1
