### ISSUE TITLE
backup fails with juju 

### ISSUE THREAD

**Issue by nishant-dash** [canonical/charm-juju-backup-all#52]
backups fail with juuju 2.9.51 and 2.9.45, I would imagine all from 2.9.45+ fail. Can we get this supported please?

```console
unit-juju-backup-all-0: 15:06:30 INFO unit.juju-backup-all/0.juju-log Check_health exporter snap.
unit-juju-backup-all-0: 15:06:30 INFO unit.juju-backup-all/0.juju-log Check_health exporter snap - Done
unit-juju-backup-all-0: 15:06:31 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-juju-backup-all-0: 15:09:42 INFO unit.juju-backup-all/0.juju-log Setting charm primary status True
unit-juju-backup-all-0: 15:09:42 WARNING unit.juju-backup-all/0.juju-log 0 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
unit-juju-backup-all-0: 15:09:42 ERROR unit.juju-backup-all/0.juju-log Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/src/utils.py", line 282, in push_ssh_keys_to_models
    with connect_controller(controller_name) as controller:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/jujubackupall/utils.py", line 46, in connect_controller
    run_async(controller.connect(controller_name))
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/jujubackupall/async_handlers.py", line 25, in run_async
    return loop.run_until_complete(func)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/juju/controller.py", line 107, in connect
    await self._connector.connect_controller(controller_name, **kwargs)
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/juju/client/connector.py", line 114, in connect_controller
    await self.connect(
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/juju/client/connector.py", line 85, in connect
    raise JujuConnectionError("juju server-version %s not supported" % juju_server_version)
juju.errors.JujuConnectionError: juju server-version 2.9.51 not supported

unit-juju-backup-all-0: 15:09:42 INFO unit.juju-backup-all/0.juju-log [config] juju client config backed up.
unit-juju-backup-all-0: 15:09:42 ERROR unit.juju-backup-all/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 170, in <module>
    main(JujuBackupAllCharm)  # pragma: no cover
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/ops/framework.py", line 342, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/ops/framework.py", line 928, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 93, in _on_do_backup_action
    backup_results = self.helper.perform_backup(omit_models=omit_models)
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/src/utils.py", line 154, in perform_backup
    backup_results = backup_processor.process_backups(omit_models=omit_models)
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/jujubackupall/process.py", line 96, in process_backups
    with connect_controller(controller_name) as controller:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/jujubackupall/utils.py", line 46, in connect_controller
    run_async(controller.connect(controller_name))
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/jujubackupall/async_handlers.py", line 25, in run_async
    return loop.run_until_complete(func)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/juju/controller.py", line 107, in connect
    await self._connector.connect_controller(controller_name, **kwargs)
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/juju/client/connector.py", line 114, in connect_controller
    await self.connect(
  File "/var/lib/juju/agents/unit-juju-backup-all-0/charm/venv/juju/client/connector.py", line 85, in connect
    raise JujuConnectionError("juju server-version %s not supported" % juju_server_version)
juju.errors.JujuConnectionError: juju server-version 2.9.51 not supported

```

**Comment by rgildein** [comment]
This should be supported by `tmp/2.9` branch (and PR #58), however right now it's just temporary support release to `latest/edge/2.9` branch. 

I'm not closing this issue yet, until we do not make decision if we will support juju 2.9 again.

**Comment by rgildein** [comment]
related: #53

**Comment by samuelallan72** [comment]
Closing because we decided to not officially support juju 2.9 any more. See internal ticket [SOLENG-1080](https://warthogs.atlassian.net/browse/SOLENG-1080) for more information about the temporary support for this use case.
